create table projects (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  pallets json,
  url text,
  name text,
  is_public boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone
);

alter table projects enable row level security;

create policy "Individuals can create projects." on projects for
    insert with check (auth.uid() = user_id);

create policy "Public can view projects. " on projects for
    select using ( true );

create policy "Individuals can update their own projects." on projects for
    update using (auth.uid() = user_id);

create policy "Individuals can delete their own projects." on projects for
    delete using (auth.uid() = user_id);